/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author ruan.lviana
 */
public class AlterarEventosParalelos extends javax.swing.JFrame {

    /**
     * Creates new form AlterarEventosParalelos
     */
    public AlterarEventosParalelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEvento = new javax.swing.JLabel();
        txtEvento = new javax.swing.JTextField();
        lblResponsavel = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblInformacoes = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        lblLocal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacoes = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alteração de eventos paralelos");
        getContentPane().setLayout(null);

        lblEvento.setText("Evento:");
        getContentPane().add(lblEvento);
        lblEvento.setBounds(40, 60, 50, 40);
        getContentPane().add(txtEvento);
        txtEvento.setBounds(120, 60, 420, 40);

        lblResponsavel.setText("Responsável:");
        getContentPane().add(lblResponsavel);
        lblResponsavel.setBounds(40, 130, 70, 40);
        getContentPane().add(txtResponsavel);
        txtResponsavel.setBounds(120, 130, 420, 40);

        lblData.setText("Data:");
        getContentPane().add(lblData);
        lblData.setBounds(40, 200, 50, 40);
        getContentPane().add(txtData);
        txtData.setBounds(120, 200, 170, 40);

        lblHora.setText("Hora:");
        getContentPane().add(lblHora);
        lblHora.setBounds(320, 200, 70, 40);
        getContentPane().add(txtHora);
        txtHora.setBounds(360, 200, 180, 40);

        lblInformacoes.setText("Informações:");
        getContentPane().add(lblInformacoes);
        lblInformacoes.setBounds(40, 370, 70, 40);
        getContentPane().add(txtLocal);
        txtLocal.setBounds(120, 260, 420, 40);

        lblLocal.setText("Local:");
        getContentPane().add(lblLocal);
        lblLocal.setBounds(40, 260, 50, 40);

        txtInformacoes.setColumns(20);
        txtInformacoes.setRows(5);
        jScrollPane1.setViewportView(txtInformacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 330, 420, 120);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(230, 500, 190, 50);

        setSize(new java.awt.Dimension(630, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarEventosParalelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblResponsavel;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextArea txtInformacoes;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtResponsavel;
    // End of variables declaration//GEN-END:variables
}
