/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.SQLException;
import dao.FestivalCinemaGramadoDao;
import javax.swing.JOptionPane;

/**
 *
 * @author ruan.lviana
 */
public class AlterarProgramacaoFilmes extends javax.swing.JFrame {

    /**
     * Creates new form AlterarProgramacaoFilmes
     */
    public AlterarProgramacaoFilmes() {
        initComponents();
    }

    public AlterarProgramacaoFilmes(String idFilme, String idProgramacao, String local, String data, String hora, String info) {
        initComponents();
        
        txtFilme.setText(idFilme);
        txtId.setText(idProgramacao);
        txtId.setEnabled(false);
        txtLocal.setText(local);
        txtData.setText(data);
        txtHora.setText(hora);
        txtInformacoes.setText(info);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        lblIdFilme = new javax.swing.JLabel();
        txtFilme = new javax.swing.JTextField();
        lblInformacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacoes = new javax.swing.JTextArea();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblLocal = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar a programação dos filmes");
        getContentPane().setLayout(null);

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(240, 470, 170, 40);

        lblIdFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdFilme.setText("Filme:");
        getContentPane().add(lblIdFilme);
        lblIdFilme.setBounds(20, 90, 80, 30);

        txtFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilmeActionPerformed(evt);
            }
        });
        getContentPane().add(txtFilme);
        txtFilme.setBounds(130, 90, 460, 30);

        lblInformacoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInformacoes.setText("Informações:");
        getContentPane().add(lblInformacoes);
        lblInformacoes.setBounds(20, 330, 90, 40);

        txtInformacoes.setColumns(20);
        txtInformacoes.setLineWrap(true);
        txtInformacoes.setRows(5);
        jScrollPane1.setViewportView(txtInformacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 290, 450, 120);

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setText("Data:");
        getContentPane().add(lblData);
        lblData.setBounds(20, 210, 80, 30);

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });
        getContentPane().add(txtData);
        txtData.setBounds(130, 210, 190, 30);

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHora.setText("Hora:");
        getContentPane().add(lblHora);
        lblHora.setBounds(350, 210, 40, 30);

        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        getContentPane().add(txtHora);
        txtHora.setBounds(400, 210, 190, 30);

        lblLocal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLocal.setText("Local:");
        getContentPane().add(lblLocal);
        lblLocal.setBounds(20, 150, 60, 30);

        txtLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalActionPerformed(evt);
            }
        });
        getContentPane().add(txtLocal);
        txtLocal.setBounds(130, 150, 460, 30);

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setText("Programação:");
        getContentPane().add(lblId);
        lblId.setBounds(20, 30, 130, 30);
        getContentPane().add(txtId);
        txtId.setBounds(130, 30, 460, 30);

        setSize(new java.awt.Dimension(646, 585));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String idFilme, idProgramacao, local, data, hora, info;
        
        idFilme = txtFilme.getText();
        idProgramacao = txtId.getText();
        local = txtLocal.getText();
        data = txtData.getText();
        hora = txtHora.getText();
        info = txtInformacoes.getText();
        
        try{
           new FestivalCinemaGramadoDao().alterarProgramacao(idFilme, idProgramacao, local, data, hora, info);
           
            JOptionPane.showMessageDialog(null, "Programação alterada com sucesso", "Alterar Programação", JOptionPane.INFORMATION_MESSAGE);
           
           txtFilme.setText("");
           txtId.setText("");
           txtLocal.setText("");
           txtData.setText("");
           txtHora.setText("");
           txtInformacoes.setText("");
           txtFilme.requestFocus();
           
           dispose();
           
        } catch(ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilmeActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarProgramacaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarProgramacaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarProgramacaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarProgramacaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarProgramacaoFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdFilme;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtFilme;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextArea txtInformacoes;
    private javax.swing.JTextField txtLocal;
    // End of variables declaration//GEN-END:variables
}
