/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.FestivalCinemaGramadoDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author fabricio.asantana1
 */
public class AlterarDadosUsu extends javax.swing.JFrame {

    /**
     * Creates new form AlterarDadosUsu
     */
    public AlterarDadosUsu() {
        initComponents();
    }

     public AlterarDadosUsu(String nome, String sobrenome, String email, String senha, String cpf, String tipo) {
        initComponents();
    
        txtNome.setText(nome);
        txtSobrenome.setText(sobrenome);
        txtEmail.setText(email);
        txtSenha.setText(senha);
        txtCpf.setText(cpf);
        cmbTipoUsuario.setSelectedItem(tipo);
        
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblSobrenome = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        lblTipoUsuario = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 30, 60, 30);

        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(210, 100, 40, 30);

        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(30, 170, 60, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(80, 30, 200, 30);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(250, 100, 360, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(80, 170, 200, 30);

        btnSalvar.setText("Salvar Informações");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(230, 270, 160, 30);

        lblCpf.setText("CPF:");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(30, 100, 40, 30);
        getContentPane().add(txtCpf);
        txtCpf.setBounds(80, 100, 120, 30);

        lblSobrenome.setText("Sobrenome:");
        getContentPane().add(lblSobrenome);
        lblSobrenome.setBounds(300, 30, 70, 30);
        getContentPane().add(txtSobrenome);
        txtSobrenome.setBounds(380, 30, 230, 30);

        lblTipoUsuario.setText("Tipo de Usuário");
        getContentPane().add(lblTipoUsuario);
        lblTipoUsuario.setBounds(300, 170, 100, 30);

        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visitante", "Cineasta", "Avaliador" }));
        getContentPane().add(cmbTipoUsuario);
        cmbTipoUsuario.setBounds(400, 170, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome, sobrenome, cpf, email, senha, tipoUsu;

        nome = txtNome.getText();
        sobrenome = txtSobrenome.getText();
        cpf = txtCpf.getText();
        email = txtEmail.getText();
        senha = txtSenha.getText();
        tipoUsu = (String) cmbTipoUsuario.getSelectedItem();

        try {
            new FestivalCinemaGramadoDao().alterarUsuario(nome, sobrenome, senha, cpf);

            JOptionPane.showMessageDialog(null, "Informações alteradas com sucesso");
           

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        } 
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarDadosUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarDadosUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarDadosUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarDadosUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarDadosUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
