/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.FestivalCinemaGramadoDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ruan.lviana
 */
public class AlterarEventosParalelos extends javax.swing.JFrame {

    /**
     * Creates new form AlterarEventosParalelos
     */
    public AlterarEventosParalelos() {
        initComponents();
    }

    public AlterarEventosParalelos(String id_evt_paral, String nome_evt_paral, String responsavel_evt_paral, String info_evt_paral,
            String local_evt_paral, String data_evt_paral, String hora_evt_paral) {
        initComponents();

        // Passando as informações do menu para os campos;
        txtId.setText(id_evt_paral);
        txtId.setEnabled(false); // Deixando o campo ID visível, porém não editável
        txtEvento.setText(nome_evt_paral);
        txtResponsavel.setText(responsavel_evt_paral);
        txtInformacoes.setText(info_evt_paral);
        txtLocal.setText(local_evt_paral);
        txtData.setText(data_evt_paral);
        txtHora.setText(hora_evt_paral);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEvento = new javax.swing.JLabel();
        txtEvento = new javax.swing.JTextField();
        lblResponsavel = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblInformacoes = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        lblLocal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacoes = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alteração de eventos paralelos");
        getContentPane().setLayout(null);

        lblEvento.setText("Evento:");
        getContentPane().add(lblEvento);
        lblEvento.setBounds(20, 100, 50, 40);
        getContentPane().add(txtEvento);
        txtEvento.setBounds(110, 100, 450, 40);

        lblResponsavel.setText("Responsável:");
        getContentPane().add(lblResponsavel);
        lblResponsavel.setBounds(20, 170, 70, 40);
        getContentPane().add(txtResponsavel);
        txtResponsavel.setBounds(110, 170, 450, 40);

        lblData.setText("Data:");
        getContentPane().add(lblData);
        lblData.setBounds(20, 240, 50, 40);
        getContentPane().add(txtData);
        txtData.setBounds(110, 240, 180, 40);

        lblHora.setText("Hora:");
        getContentPane().add(lblHora);
        lblHora.setBounds(330, 240, 70, 40);
        getContentPane().add(txtHora);
        txtHora.setBounds(380, 240, 180, 40);

        lblInformacoes.setText("Informações:");
        getContentPane().add(lblInformacoes);
        lblInformacoes.setBounds(20, 420, 70, 40);
        getContentPane().add(txtLocal);
        txtLocal.setBounds(110, 310, 450, 40);

        lblLocal.setText("Local:");
        getContentPane().add(lblLocal);
        lblLocal.setBounds(20, 310, 50, 40);

        txtInformacoes.setColumns(20);
        txtInformacoes.setLineWrap(true);
        txtInformacoes.setRows(5);
        txtInformacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtInformacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 380, 450, 120);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(220, 530, 190, 50);

        lblId.setText("ID:");
        getContentPane().add(lblId);
        lblId.setBounds(20, 30, 50, 40);
        getContentPane().add(txtId);
        txtId.setBounds(110, 30, 450, 40);

        setSize(new java.awt.Dimension(630, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // Varíaveis;
        String id_evt_paral, nome_evt_paral, responsavel_evt_paral, info_evt_paral, local_evt_paral, data_evt_paral, hora_evt_paral;

        // Pegando as informações dos campos;
        id_evt_paral = txtId.getText();
        nome_evt_paral = txtEvento.getText();
        responsavel_evt_paral = txtResponsavel.getText();
        info_evt_paral = txtInformacoes.getText();
        local_evt_paral = txtLocal.getText();
        data_evt_paral = txtData.getText();
        hora_evt_paral = txtHora.getText();

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            new FestivalCinemaGramadoDao().alterarEventosParalelos(id_evt_paral, nome_evt_paral, responsavel_evt_paral, info_evt_paral, local_evt_paral, data_evt_paral, hora_evt_paral);

            // Mensagem para dizer que o evento foi cadastro;
            JOptionPane.showMessageDialog(null, "Evento alterado com sucesso", "Alteração de Evento Paralelo", JOptionPane.INFORMATION_MESSAGE);

            // Fechar a tela após a execução dos comandos do "try" ou do "catch";
            dispose();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarEventosParalelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblResponsavel;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextArea txtInformacoes;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtResponsavel;
    // End of variables declaration//GEN-END:variables
}
