/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author ruan.lviana
 */
public class CadastrarSubmissaoFilmes extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarSubmissaoFilmes
     */
    public CadastrarSubmissaoFilmes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFilme = new javax.swing.JLabel();
        txtFilme = new javax.swing.JTextField();
        lblDuracao = new javax.swing.JLabel();
        txtDuracao = new javax.swing.JTextField();
        lblClassificacao = new javax.swing.JLabel();
        txtClassificacao = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        lblSobrenomeDiretor = new javax.swing.JLabel();
        txtNomeDiretor = new javax.swing.JTextField();
        txtSobrenomeDiretor = new javax.swing.JTextField();
        lblInformacoes = new javax.swing.JLabel();
        lblNomeDiretor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacoes = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro da submissão de filmes");
        getContentPane().setLayout(null);

        lblFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFilme.setText("Filme:");
        getContentPane().add(lblFilme);
        lblFilme.setBounds(40, 60, 50, 40);

        txtFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilmeActionPerformed(evt);
            }
        });
        getContentPane().add(txtFilme);
        txtFilme.setBounds(90, 60, 550, 40);

        lblDuracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuracao.setText("Duração:");
        getContentPane().add(lblDuracao);
        lblDuracao.setBounds(40, 130, 54, 40);

        txtDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDuracao);
        txtDuracao.setBounds(100, 130, 120, 40);

        lblClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClassificacao.setText("Classificação:");
        getContentPane().add(lblClassificacao);
        lblClassificacao.setBounds(230, 130, 80, 40);

        txtClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassificacaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtClassificacao);
        txtClassificacao.setBounds(320, 130, 110, 40);

        lblGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGenero.setText("Gênero:");
        getContentPane().add(lblGenero);
        lblGenero.setBounds(440, 130, 60, 40);

        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(txtGenero);
        txtGenero.setBounds(500, 130, 140, 40);

        lblSobrenomeDiretor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSobrenomeDiretor.setText("Sobrenome Diretor:");
        getContentPane().add(lblSobrenomeDiretor);
        lblSobrenomeDiretor.setBounds(310, 200, 120, 40);

        txtNomeDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDiretorActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeDiretor);
        txtNomeDiretor.setBounds(130, 200, 170, 40);

        txtSobrenomeDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeDiretorActionPerformed(evt);
            }
        });
        getContentPane().add(txtSobrenomeDiretor);
        txtSobrenomeDiretor.setBounds(440, 200, 200, 40);

        lblInformacoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInformacoes.setText("Informações:");
        getContentPane().add(lblInformacoes);
        lblInformacoes.setBounds(40, 300, 90, 40);

        lblNomeDiretor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeDiretor.setText("Nome Diretor:");
        getContentPane().add(lblNomeDiretor);
        lblNomeDiretor.setBounds(40, 200, 90, 40);

        txtInformacoes.setColumns(20);
        txtInformacoes.setRows(5);
        jScrollPane1.setViewportView(txtInformacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 270, 510, 120);

        btnSalvar.setText("Salvar");
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(250, 430, 230, 50);

        setSize(new java.awt.Dimension(730, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilmeActionPerformed

    private void txtDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracaoActionPerformed

    private void txtClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassificacaoActionPerformed

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtNomeDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDiretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDiretorActionPerformed

    private void txtSobrenomeDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSobrenomeDiretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeDiretorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarSubmissaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarSubmissaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarSubmissaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarSubmissaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarSubmissaoFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblFilme;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblNomeDiretor;
    private javax.swing.JLabel lblSobrenomeDiretor;
    private javax.swing.JTextField txtClassificacao;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtFilme;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextArea txtInformacoes;
    private javax.swing.JTextField txtNomeDiretor;
    private javax.swing.JTextField txtSobrenomeDiretor;
    // End of variables declaration//GEN-END:variables
}
