/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.FestivalCinemaGramadoDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ruan.lviana
 */
public class CadastrarEventosParalelos extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarEventosParalelos
     */
    public CadastrarEventosParalelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEvento = new javax.swing.JLabel();
        txtEvento = new javax.swing.JTextField();
        lblResponsavel = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblInformacoes = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        lblLocal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacoes = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de eventos paralelos");
        getContentPane().setLayout(null);

        lblEvento.setText("Evento:");
        getContentPane().add(lblEvento);
        lblEvento.setBounds(40, 90, 50, 40);
        getContentPane().add(txtEvento);
        txtEvento.setBounds(120, 90, 420, 40);

        lblResponsavel.setText("Responsável:");
        getContentPane().add(lblResponsavel);
        lblResponsavel.setBounds(40, 160, 70, 40);
        getContentPane().add(txtResponsavel);
        txtResponsavel.setBounds(120, 160, 420, 40);

        lblData.setText("Data:");
        getContentPane().add(lblData);
        lblData.setBounds(40, 230, 50, 40);
        getContentPane().add(txtData);
        txtData.setBounds(120, 230, 170, 40);

        lblHora.setText("Hora:");
        getContentPane().add(lblHora);
        lblHora.setBounds(320, 230, 70, 40);
        getContentPane().add(txtHora);
        txtHora.setBounds(360, 230, 180, 40);

        lblInformacoes.setText("Informações:");
        getContentPane().add(lblInformacoes);
        lblInformacoes.setBounds(40, 400, 70, 40);
        getContentPane().add(txtLocal);
        txtLocal.setBounds(120, 290, 420, 40);

        lblLocal.setText("Local:");
        getContentPane().add(lblLocal);
        lblLocal.setBounds(40, 290, 50, 40);

        txtInformacoes.setColumns(20);
        txtInformacoes.setRows(5);
        jScrollPane1.setViewportView(txtInformacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 360, 420, 120);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(230, 530, 190, 50);

        lblId.setText("ID:");
        getContentPane().add(lblId);
        lblId.setBounds(40, 30, 50, 40);
        getContentPane().add(txtId);
        txtId.setBounds(120, 30, 420, 40);

        setSize(new java.awt.Dimension(630, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String id_evt_paral, nome_evt_paral, responsavel_evt_paral, info_evt_paral, local_evt_paral, data_evt_paral, hora_evt_paral;
        
        // Pegando as informações dos campos;
        id_evt_paral = txtId.getText();
        nome_evt_paral = txtEvento.getText();
        responsavel_evt_paral = txtResponsavel.getText();
        info_evt_paral = txtInformacoes.getText();
        local_evt_paral = txtLocal.getText();
        data_evt_paral = txtData.getText();
        hora_evt_paral = txtHora.getText();
        

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            new FestivalCinemaGramadoDao().cadastrarEventosParalelos(id_evt_paral, nome_evt_paral, responsavel_evt_paral, info_evt_paral, local_evt_paral, data_evt_paral, hora_evt_paral);

            // Mensagem para dizer que o filme foi cadastro;
            JOptionPane.showMessageDialog(null, "Evento cadastro com sucesso", "Cadastro de Eventos Paralelos", JOptionPane.INFORMATION_MESSAGE);

            // Limpar a tela e reposicionar o cursor do mouse;
            txtId.setText("");
            txtEvento.setText("");
            txtResponsavel.setText("");
            txtInformacoes.setText("");
            txtLocal.setText("");
            txtData.setText("");
            txtHora.setText("");
            txtId.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        } catch (SQLException ex) {
            String erro = ex.getMessage();

            if (erro.contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "O evento já foi cadastrado", "Erro no cadastro", JOptionPane.WARNING_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarEventosParalelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarEventosParalelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblResponsavel;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextArea txtInformacoes;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtResponsavel;
    // End of variables declaration//GEN-END:variables
}
