/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.FestivalCinemaGramadoDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ruan.lviana
 */
public class CadastrarProgramacaoFilmes extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarProgramacaoFilmes
     */
    public CadastrarProgramacaoFilmes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdFilme = new javax.swing.JLabel();
        txtFilme = new javax.swing.JTextField();
        lblInformacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacoes = new javax.swing.JTextArea();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblLocal = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblIdProgramacao = new javax.swing.JLabel();
        txtIdProgramacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastar a programação dos filmes");
        getContentPane().setLayout(null);

        lblIdFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdFilme.setText("Filme:");
        getContentPane().add(lblIdFilme);
        lblIdFilme.setBounds(10, 30, 80, 40);

        txtFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilmeActionPerformed(evt);
            }
        });
        getContentPane().add(txtFilme);
        txtFilme.setBounds(70, 30, 510, 40);

        lblInformacoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInformacoes.setText("Informações:");
        getContentPane().add(lblInformacoes);
        lblInformacoes.setBounds(20, 370, 90, 40);

        txtInformacoes.setColumns(20);
        txtInformacoes.setLineWrap(true);
        txtInformacoes.setRows(5);
        jScrollPane1.setViewportView(txtInformacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 340, 450, 120);

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setText("Data:");
        getContentPane().add(lblData);
        lblData.setBounds(20, 250, 80, 40);

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });
        getContentPane().add(txtData);
        txtData.setBounds(80, 250, 220, 40);

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHora.setText("Hora:");
        getContentPane().add(lblHora);
        lblHora.setBounds(310, 250, 40, 40);

        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        getContentPane().add(txtHora);
        txtHora.setBounds(360, 250, 220, 40);

        lblLocal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLocal.setText("Local:");
        getContentPane().add(lblLocal);
        lblLocal.setBounds(20, 180, 60, 40);

        txtLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalActionPerformed(evt);
            }
        });
        getContentPane().add(txtLocal);
        txtLocal.setBounds(80, 180, 500, 40);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(200, 500, 220, 40);

        lblIdProgramacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdProgramacao.setText("Programação:");
        getContentPane().add(lblIdProgramacao);
        lblIdProgramacao.setBounds(10, 100, 130, 40);
        getContentPane().add(txtIdProgramacao);
        txtIdProgramacao.setBounds(120, 100, 460, 40);

        setSize(new java.awt.Dimension(624, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilmeActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // Variáveis;
        String idFilme, idProgramacao, local, data, hora, info;

        // Atribuindo as variáveis aos campos;
        idFilme = txtFilme.getText();
        idProgramacao = txtIdProgramacao.getText();
        local = txtLocal.getText();
        data = txtData.getText();
        hora = txtHora.getText();
        info = txtInformacoes.getText();

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            new FestivalCinemaGramadoDao().cadastrarProgramacao(idFilme, idProgramacao, local, data, hora, info);

            // Mensagem para dizer que a programação foi cadastrada;
            JOptionPane.showMessageDialog(null, "Programação cadastrada com sucesso", "Cadastro da Programação", JOptionPane.INFORMATION_MESSAGE);

            // Limpando os campos;
            txtFilme.setText("");
            txtIdProgramacao.setText("");
            txtLocal.setText("");
            txtData.setText("");
            txtHora.setText("");
            txtInformacoes.setText("");
            txtIdProgramacao.requestFocus(); // Reposicionando o cursor do mouse;

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        } catch (SQLException ex) {
            String erro = ex.getMessage();

            if (erro.contains("cannot be null")) {
                JOptionPane.showMessageDialog(null, "Filme não encontrado! Verifique se o nome do filme está correto", "Filme não encontrado", JOptionPane.WARNING_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProgramacaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProgramacaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProgramacaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProgramacaoFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProgramacaoFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIdFilme;
    private javax.swing.JLabel lblIdProgramacao;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtFilme;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdProgramacao;
    private javax.swing.JTextArea txtInformacoes;
    private javax.swing.JTextField txtLocal;
    // End of variables declaration//GEN-END:variables
}
