/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.FestivalCinemaGramadoDao;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author arauj
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pswSenha = new javax.swing.JPasswordField();
        btnEntrar4 = new javax.swing.JButton();
        lblMsgCadastro = new javax.swing.JLabel();
        bntAbrirTelaCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);

        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(20, 30, 50, 30);

        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(20, 100, 50, 30);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(80, 30, 360, 30);
        getContentPane().add(pswSenha);
        pswSenha.setBounds(80, 100, 360, 30);

        btnEntrar4.setText("Entrar");
        btnEntrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar4);
        btnEntrar4.setBounds(190, 170, 90, 30);

        lblMsgCadastro.setText("Não tem cadastro? Faça o seu cadastro agora mesmo!");
        getContentPane().add(lblMsgCadastro);
        lblMsgCadastro.setBounds(30, 240, 290, 30);

        bntAbrirTelaCadastro.setText("Cadastre-se");
        bntAbrirTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAbrirTelaCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(bntAbrirTelaCadastro);
        bntAbrirTelaCadastro.setBounds(330, 240, 100, 30);

        setSize(new java.awt.Dimension(489, 314));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar4ActionPerformed
        String email, senha;

        email = txtEmail.getText();
        senha = pswSenha.getText();

        try {
            ResultSet usuario = new FestivalCinemaGramadoDao().loginUsuario(email, senha);
            if (usuario.next()) {
                String tipoUsu;

                tipoUsu = usuario.getString("tipo");
                
                dispose();
                new MenuPrincipal(tipoUsu).setVisible(true);
            
            } else {
                JOptionPane.showMessageDialog(null, "Usuário não identificado");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnEntrar4ActionPerformed

    private void bntAbrirTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAbrirTelaCadastroActionPerformed
        new CadastrarUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_bntAbrirTelaCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAbrirTelaCadastro;
    private javax.swing.JButton btnEntrar4;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMsgCadastro;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
