/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.FestivalCinemaGramadoDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author arauj
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    public MenuPrincipal(String tipoUsu) {
        initComponents();

        // Delimitando o que cada usuário pode ver e fazer no menu;
        if (tipoUsu.equalsIgnoreCase("Visitante")) {
            itmBuscarUsuario.setVisible(false);
            itmListarUsuario.setVisible(false);
            itmExcluirUsuario.setVisible(false);
            mnuSubmissaoFilmes.setVisible(false);
            itmCadastrarProgramacao.setVisible(false);
            itmBuscarProgramacao.setVisible(false);
            itmAlterarProgramacao.setVisible(false);
            itmExcluirProgramacao.setVisible(false);
            mnuSubmissaoFilmes.setVisible(false);
            itmCadastrarEventos.setVisible(false);
            itmAlterarEventos.setVisible(false);
            itmBuscarEventos.setVisible(false);
            itmExcluirEventos.setVisible(false);

        } else if (tipoUsu.equalsIgnoreCase("Cineasta")) {
            itmBuscarUsuario.setVisible(false);
            itmListarUsuario.setVisible(false);
            itmExcluirUsuario.setVisible(false);
            itmCadastrarProgramacao.setVisible(false);
            itmBuscarProgramacao.setVisible(false);
            itmAlterarProgramacao.setVisible(false);
            itmExcluirProgramacao.setVisible(false);
            itmBuscarEventos.setVisible(false);

        } else if (tipoUsu.equalsIgnoreCase("Avaliador")) {
            itmBuscarUsuario.setVisible(false);
            itmListarUsuario.setVisible(false);
            itmExcluirUsuario.setVisible(false);
            mnuProgramacaoFilmes.setVisible(false);
            mnuSubmissaoFilmes.setVisible(false);
            mnuEventosParalelos.setVisible(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagemPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuario = new javax.swing.JMenu();
        itmAlterarInfoUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmBuscarUsuario = new javax.swing.JMenuItem();
        itmListarUsuario = new javax.swing.JMenuItem();
        itmExcluirUsuario = new javax.swing.JMenuItem();
        mnuProgramacaoFilmes = new javax.swing.JMenu();
        itmCadastrarProgramacao = new javax.swing.JMenuItem();
        itmVerFilmes = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itmBuscarProgramacao = new javax.swing.JMenuItem();
        itmAlterarProgramacao = new javax.swing.JMenuItem();
        itmExcluirProgramacao = new javax.swing.JMenuItem();
        mnuSubmissaoFilmes = new javax.swing.JMenu();
        itmCadastrarFilme = new javax.swing.JMenuItem();
        itmListarFilme = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itmAlterarFilme = new javax.swing.JMenuItem();
        itmBuscarFilme = new javax.swing.JMenuItem();
        itmExcluirFilme = new javax.swing.JMenuItem();
        mnuEventosParalelos = new javax.swing.JMenu();
        itmCadastrarEventos = new javax.swing.JMenuItem();
        itmListarEventos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itmAlterarEventos = new javax.swing.JMenuItem();
        itmBuscarEventos = new javax.swing.JMenuItem();
        itmExcluirEventos = new javax.swing.JMenuItem();
        mnuMaisInformacoes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(null);

        lblImagemPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/img-festival-cinema-full.jpg"))); // NOI18N
        lblImagemPrincipal.setText("jLabel1");
        getContentPane().add(lblImagemPrincipal);
        lblImagemPrincipal.setBounds(-10, -30, 840, 560);

        mnuUsuario.setText("Usuario");

        itmAlterarInfoUsuario.setText("Alterar Informações");
        itmAlterarInfoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarInfoUsuarioActionPerformed(evt);
            }
        });
        mnuUsuario.add(itmAlterarInfoUsuario);
        mnuUsuario.add(jSeparator1);

        itmBuscarUsuario.setText("Buscar");
        itmBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuario.add(itmBuscarUsuario);

        itmListarUsuario.setText("Listar");
        itmListarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuario.add(itmListarUsuario);

        itmExcluirUsuario.setText("Excluir");
        itmExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirUsuarioActionPerformed(evt);
            }
        });
        mnuUsuario.add(itmExcluirUsuario);

        jMenuBar1.add(mnuUsuario);

        mnuProgramacaoFilmes.setText("Programação dos Filmes");

        itmCadastrarProgramacao.setText("Cadastrar Programação");
        itmCadastrarProgramacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarProgramacaoActionPerformed(evt);
            }
        });
        mnuProgramacaoFilmes.add(itmCadastrarProgramacao);

        itmVerFilmes.setText("Ver Filmes");
        itmVerFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmVerFilmesActionPerformed(evt);
            }
        });
        mnuProgramacaoFilmes.add(itmVerFilmes);
        mnuProgramacaoFilmes.add(jSeparator4);

        itmBuscarProgramacao.setText("Buscar");
        itmBuscarProgramacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarProgramacaoActionPerformed(evt);
            }
        });
        mnuProgramacaoFilmes.add(itmBuscarProgramacao);

        itmAlterarProgramacao.setText("Alterar");
        itmAlterarProgramacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarProgramacaoActionPerformed(evt);
            }
        });
        mnuProgramacaoFilmes.add(itmAlterarProgramacao);

        itmExcluirProgramacao.setText("Excluir");
        itmExcluirProgramacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirProgramacaoActionPerformed(evt);
            }
        });
        mnuProgramacaoFilmes.add(itmExcluirProgramacao);

        jMenuBar1.add(mnuProgramacaoFilmes);

        mnuSubmissaoFilmes.setText("Submissão de Filmes");

        itmCadastrarFilme.setText("Cadastrar Filme");
        itmCadastrarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarFilmeActionPerformed(evt);
            }
        });
        mnuSubmissaoFilmes.add(itmCadastrarFilme);

        itmListarFilme.setText("Listar Filme");
        itmListarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarFilmeActionPerformed(evt);
            }
        });
        mnuSubmissaoFilmes.add(itmListarFilme);
        mnuSubmissaoFilmes.add(jSeparator3);

        itmAlterarFilme.setText("Alterar Filme");
        itmAlterarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarFilmeActionPerformed(evt);
            }
        });
        mnuSubmissaoFilmes.add(itmAlterarFilme);

        itmBuscarFilme.setText("Buscar Filme");
        itmBuscarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarFilmeActionPerformed(evt);
            }
        });
        mnuSubmissaoFilmes.add(itmBuscarFilme);

        itmExcluirFilme.setText("Excluir Filme");
        itmExcluirFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirFilmeActionPerformed(evt);
            }
        });
        mnuSubmissaoFilmes.add(itmExcluirFilme);

        jMenuBar1.add(mnuSubmissaoFilmes);

        mnuEventosParalelos.setText("Eventos Paralelos");

        itmCadastrarEventos.setText("Cadastrar Eventos");
        itmCadastrarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarEventosActionPerformed(evt);
            }
        });
        mnuEventosParalelos.add(itmCadastrarEventos);

        itmListarEventos.setText("Listar Eventos");
        itmListarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarEventosActionPerformed(evt);
            }
        });
        mnuEventosParalelos.add(itmListarEventos);
        mnuEventosParalelos.add(jSeparator2);

        itmAlterarEventos.setText("Alterar Eventos");
        itmAlterarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarEventosActionPerformed(evt);
            }
        });
        mnuEventosParalelos.add(itmAlterarEventos);

        itmBuscarEventos.setText("Buscar Eventos");
        itmBuscarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarEventosActionPerformed(evt);
            }
        });
        mnuEventosParalelos.add(itmBuscarEventos);

        itmExcluirEventos.setText("Excluir Eventos");
        itmExcluirEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirEventosActionPerformed(evt);
            }
        });
        mnuEventosParalelos.add(itmExcluirEventos);

        jMenuBar1.add(mnuEventosParalelos);

        mnuMaisInformacoes.setText("Mais Informações");
        mnuMaisInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMaisInformacoesMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuMaisInformacoes);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(829, 536));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarEventosActionPerformed
        new CadastrarEventosParalelos().setVisible(true); // Instancindo a classe e deixando ela visível;
    }//GEN-LAST:event_itmCadastrarEventosActionPerformed

    private void itmBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarUsuarioActionPerformed
        // Variável para pegar o cpf do usuário;
        String cpfUsu;

        // Pegando o cpf do usuário;
        cpfUsu = JOptionPane.showInputDialog(null, "Digite o CPF do usuário", "Buscar Usuário", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            ResultSet usuario = new FestivalCinemaGramadoDao().buscarUsuario(cpfUsu);

            if (usuario.next()) { // Se o usuário for encontrado;
                // Variáveis para pegar os dados do usuário;
                String nome, sobrenome, cpf, email, senha, tipoUsu;

                // Atribuindo as variáveis aos campos que contém os dados;
                nome = usuario.getString("nome_usu");
                sobrenome = usuario.getString("sobrenome_usu");
                cpf = usuario.getString("cpf_usu");
                email = usuario.getString("email_usu");
                senha = usuario.getString("senha_usu");
                tipoUsu = usuario.getString("tipo_usu");

                // Mensagem trazendo todos os dados do usuário; 
                JOptionPane.showMessageDialog(null, "Usuário: " + nome + " " + sobrenome
                        + "\n" + "CPF: " + cpf
                        + "\n" + "E-Mail: " + email
                        + "\n" + "Senha: " + senha
                        + "\n" + "Tipo de Usuário: " + tipoUsu);

            } else { // Se o usuário não for encontrado;
                JOptionPane.showMessageDialog(null, "Usuario não encontrado", "Buscar Usuário", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_itmBuscarUsuarioActionPerformed

    private void itmAlterarInfoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarInfoUsuarioActionPerformed
        // Variável para pegar o cpf do usuário;
        String cpfUsu;

        // Pegando o cpd do usuário;
        cpfUsu = JOptionPane.showInputDialog(null, "Digite o seu CPF para entrar no campo alterar!", "Alterar Dados", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            ResultSet usuario = new FestivalCinemaGramadoDao().buscarUsuario(cpfUsu);

            if (usuario.next()) { // Se o usuário for encontrado;
                // Variáveis para pegar os dados do usuário;
                String nome, sobrenome, cpf, email, senha, tipoUsu;

                // Atribuindo as variáveis aos campos que contém os dados;
                nome = usuario.getString("nome_usu");
                sobrenome = usuario.getString("sobrenome_usu");
                cpf = usuario.getString("cpf_usu");
                email = usuario.getString("email_usu");
                senha = usuario.getString("senha_usu");
                tipoUsu = usuario.getString("tipo_usu");

                // Instanciando a classe que altera os dados do usuário;
                new AlterarDadosUsuario(nome, sobrenome, cpf, email, senha, tipoUsu).setVisible(true);

            } else { // Se o usuário não for encontrado;
                JOptionPane.showMessageDialog(null, "Usuario não encontrado", "Buscar Usuário", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarInfoUsuarioActionPerformed

    private void itmExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirUsuarioActionPerformed
        // Variável para pegar o cpf do usuário;
        String cpf;

        // Pegando o cpf do usuário;
        cpf = JOptionPane.showInputDialog(null, "Digite o CPF do usuário para excluí-lo", "Exluir Usuário", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            int resultado = new FestivalCinemaGramadoDao().excluirUsuario(cpf);

            if (resultado == 1) { // Se o usuário for encontrado e o seus dados excluídos;
                JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso", "Excluir Usuário", JOptionPane.INFORMATION_MESSAGE);

            } else { // Se o usuário não for encontrado;
                JOptionPane.showMessageDialog(null, "Usuário não encontrado", "Excluir Usuário", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_itmExcluirUsuarioActionPerformed

    private void itmCadastrarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarFilmeActionPerformed
        new CadastrarSubmissaoFilmes().setVisible(true); // Instanciando a classe e deixando ela visível;
    }//GEN-LAST:event_itmCadastrarFilmeActionPerformed

    private void itmBuscarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarFilmeActionPerformed
        // Variável para pegar o código da submissão do filme;
        String codFilme;

        // Pegando o código da submissão do filme;
        codFilme = JOptionPane.showInputDialog(null, "Digite o código do filme para a busca", "Buscar Filme", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            ResultSet filme = new FestivalCinemaGramadoDao().buscarFilme(codFilme);

            if (filme.next()) { // Se a submissão de filme for encontrada;
                // Variável para pegar todos os dados da submissão;
                String id, film, duracao, classificacao, genero, nomeDiretor, sobrenomeDiretor, informacoes;

                // Atribuindo as variáveis aos campos com os dados;
                id = filme.getString("id_sub_film");
                film = filme.getString("nome_sub_film");
                duracao = filme.getString("duracao_sub_film");
                classificacao = filme.getString("faixa_etaria_sub_film");
                genero = filme.getString("categoria_sub_film");
                nomeDiretor = filme.getString("nome_diretor_sub_film");
                sobrenomeDiretor = filme.getString("sobrenome_diretor_sub_film");
                informacoes = filme.getString("info_sub_film");

                // Mensagem trazendo todos os dados da submissão do filme;
                JOptionPane.showMessageDialog(null, "ID: " + id
                        + "\n" + "Nome do filme: " + film
                        + "\n" + "Duração: " + duracao
                        + "\n" + "Classificação: " + classificacao
                        + "\n" + "Gênero: " + genero
                        + "\n" + "Nome do diretor: " + nomeDiretor
                        + "\n" + "Sobrenome do diretor: " + sobrenomeDiretor
                        + "\n" + "Informações adicionais: " + informacoes);

            } else { // Se a submissão do filme não for encontrada;
                JOptionPane.showMessageDialog(null, "Filme não encontrado", "Buscar Filme", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmBuscarFilmeActionPerformed

    private void itmListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarUsuarioActionPerformed
        new ListarUsuario().setVisible(true); // Instancindo a classe e deixando ela visível;
    }//GEN-LAST:event_itmListarUsuarioActionPerformed

    private void itmListarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarFilmeActionPerformed
        new ListarSubmissaoFilmes().setVisible(true); // Instancindo a classe e deixando ela visível;
    }//GEN-LAST:event_itmListarFilmeActionPerformed

    private void itmAlterarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarFilmeActionPerformed
        // Váriável para pegar o código da submissão do filme;
        String codFilme;

        // Pegando o código da submissão do filme para alterar;
        codFilme = JOptionPane.showInputDialog(null, "Digite o código do filme para a alteração", "Alterar Filme", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            ResultSet filme = new FestivalCinemaGramadoDao().buscarFilme(codFilme);

            if (filme.next()) { // Se o filme for encontrado;
                // Variáveis que pegaram os valores dos campos;
                String id, film, duracao, classificacao, genero, nomeDiretor, sobrenomeDiretor, informacoes;

                // Associando as variáveis aos dados armazenados nas colunas da tabela;
                id = filme.getString("id_sub_film");
                film = filme.getString("nome_sub_film");
                duracao = filme.getString("duracao_sub_film");
                classificacao = filme.getString("faixa_etaria_sub_film");
                genero = filme.getString("categoria_sub_film");
                nomeDiretor = filme.getString("nome_diretor_sub_film");
                sobrenomeDiretor = filme.getString("sobrenome_diretor_sub_film");
                informacoes = filme.getString("info_sub_film");

                // Instanciando a classe "AlterarSubmissaoFilmes" para passar os dados das variáveis;
                new AlterarSubmissaoFilmes(id, film, duracao, classificacao, genero, nomeDiretor, sobrenomeDiretor, informacoes).setVisible(true);

            } else { // Caso não encontre as informações do filme;
                JOptionPane.showMessageDialog(null, "Filme não encontrado", "Buscar Filme", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarFilmeActionPerformed

    private void itmExcluirFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirFilmeActionPerformed
        // Variável para pegar o código da submissão do filme;
        String codFilme;

        // Pegando o código da submissão do filme para a exclusão;
        codFilme = JOptionPane.showInputDialog(null, "Digite o código do filme para a exclusão", "Excluir Filme", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            int retorno = new FestivalCinemaGramadoDao().excluirSubmissaoFilmes(codFilme);

            if (retorno == 1) { // Se a submissão for encontrado e a mesma for excluida;
                JOptionPane.showMessageDialog(null, "Filme excluído com sucesso", "Excluir Filme", JOptionPane.INFORMATION_MESSAGE);

            } else { // Se a submissão não for encontrada;
                JOptionPane.showMessageDialog(null, "Filme não encontrado", "Excluir Filme", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmExcluirFilmeActionPerformed

    private void itmVerFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmVerFilmesActionPerformed
        new ListarProgramacaoFilmes().setVisible(true); // Instancindo a classe e deixando ela visível;
    }//GEN-LAST:event_itmVerFilmesActionPerformed

    private void itmCadastrarProgramacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarProgramacaoActionPerformed
        new CadastrarProgramacaoFilmes().setVisible(true); // Instancindo a classe e deixando ela visível;
    }//GEN-LAST:event_itmCadastrarProgramacaoActionPerformed

    private void mnuMaisInformacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMaisInformacoesMouseClicked
        new MaisInformacoes().setVisible(true); // Instancindo a classe e deixando ela visível;
    }//GEN-LAST:event_mnuMaisInformacoesMouseClicked

    private void itmListarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarEventosActionPerformed
        new ListarEventosParalelos().setVisible(true); // Instancindo a classe e deixando ela visível;
    }//GEN-LAST:event_itmListarEventosActionPerformed

    private void itmAlterarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarEventosActionPerformed
        // Váriável para pegar pegar o código do evento paralelo;
        String id_evt_paral;

        // Pegando o código do evento para a alteração;
        id_evt_paral = JOptionPane.showInputDialog(null, "Digite o código do evento para a alteração", "Alterar Evento Paralelo", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            ResultSet evento = new FestivalCinemaGramadoDao().buscarEventosParalelos(id_evt_paral);

            if (evento.next()) { // Se o evento for encontrado;
                // Variáveis que pegaram os valores dos campos;
                String id, nome, responsavel, info, local_evt, data_evt, hora_evt;

                // Associando as variáveis aos dados armazenados nas colunas da tabela;
                id = evento.getString("id_evt_paral");
                nome = evento.getString("nome_evt_paral");
                responsavel = evento.getString("responsavel_evt_paral");
                info = evento.getString("info_evt_paral");
                local_evt = evento.getString("local_evt_paral");
                data_evt = evento.getString("data_evt_paral");
                hora_evt = evento.getString("hora_evt_paral");

                // Instanciando a classe "AlterarEventosParalelos" para passar os dados das variáveis;
                new AlterarEventosParalelos(id, nome, responsavel, info, local_evt, data_evt, hora_evt).setVisible(true);

            } else { // Caso não encontre as informações do Evento;
                JOptionPane.showMessageDialog(null, "Evento não encontrado", "Buscar Evento", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarEventosActionPerformed

    private void itmBuscarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarEventosActionPerformed
        // Variável para pegar o código do evento paralelo;
        String id_evt_paral;

        // Pegando o código do evento paralelo;
        id_evt_paral = JOptionPane.showInputDialog(null, "Digite o código do evento para a busca", "Buscar evento paralelo", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            ResultSet evento = new FestivalCinemaGramadoDao().buscarEventosParalelos(id_evt_paral);

            if (evento.next()) { // Se o evento for encontrado;
                // Varivéis para pegar todos os dados do evento;
                String id, nome, responsavel, info, local_evt, data_evt, hora_evt;

                // Atribuindo as variáveis os campos conténdo os dados;
                id = evento.getString("id_evt_paral");
                nome = evento.getString("nome_evt_paral");
                responsavel = evento.getString("responsavel_evt_paral");
                info = evento.getString("info_evt_paral");
                local_evt = evento.getString("local_evt_paral");
                data_evt = evento.getString("data_evt_paral");
                hora_evt = evento.getString("hora_evt_paral");

                // Mensagem que contém todos os dados da busca;
                JOptionPane.showMessageDialog(null, "ID: " + id
                        + "\n" + "Nome do evento: " + nome
                        + "\n" + "Responsável: " + responsavel
                        + "\n" + "Informações: " + info
                        + "\n" + "Local: " + local_evt
                        + "\n" + "Data: " + data_evt
                        + "\n" + "Hora: " + hora_evt,
                        "Busca Evento Paralelo", JOptionPane.INFORMATION_MESSAGE);

            } else { // Se o evento não for encontrado;
                JOptionPane.showMessageDialog(null, "Evento não encontrado", "Buscar evento paralelo", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmBuscarEventosActionPerformed

    private void itmExcluirEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirEventosActionPerformed
        // Variável para pegar o código do evento paralelo;
        String id_evt_paral;

        // Pegando o código do evento paralelo;
        id_evt_paral = JOptionPane.showInputDialog(null, "Digite o código do evento para a exclusão", "Excluir Evento", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            int retorno = new FestivalCinemaGramadoDao().excluirEventosParalelos(id_evt_paral);

            if (retorno == 1) { // Se o evento for encontrado e seus dados excluido;
                JOptionPane.showMessageDialog(null, "Evento excluído com sucesso", "Excluir Evento", JOptionPane.INFORMATION_MESSAGE);

            } else { // Se o evento não for encontrado;
                JOptionPane.showMessageDialog(null, "Evento não encontrado", "Excluir Evento", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmExcluirEventosActionPerformed

    private void itmBuscarProgramacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarProgramacaoActionPerformed
        // Variável para pegar o código da programação;
        String codProgramacao;

        // Pegando o código da programação;
        codProgramacao = JOptionPane.showInputDialog(null, "Digite o código da programação para busca-lo", "Buscar Programação", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            ResultSet programacao = new FestivalCinemaGramadoDao().buscarProgramacao(codProgramacao);

            if (programacao.next()) { // Se a programação for encontrada;
                // Variáveis para pegar todos os dados da programação;
                String idFilme, idProgramacao, local, data, hora, info;

                // Pegando todos os dados da programação;
                idFilme = programacao.getString("id_sub_film");
                idProgramacao = programacao.getString("id_prog_film");
                local = programacao.getString("local_prog_film");
                data = programacao.getString("data_prog_film");
                hora = programacao.getString("hora_prog_film");
                info = programacao.getString("info_prog_film");

                // Mensagem para mostrar todos os dados que foram buscados; 
                JOptionPane.showMessageDialog(null, "ID do Filme: " + idFilme
                        + "\n" + "ID da Programação: " + idProgramacao
                        + "\n" + "Local: " + local
                        + "\n" + "Data: " + data
                        + "\n" + "Hora: " + hora
                        + "\n" + "Informações: " + info,
                        "Buscar Programação", JOptionPane.INFORMATION_MESSAGE);

            } else { // Se a programação não for encontrada;
                JOptionPane.showMessageDialog(null, "Programação não encontrada", "Buscar Programação", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmBuscarProgramacaoActionPerformed

    private void itmAlterarProgramacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarProgramacaoActionPerformed
        // Variável para pegar o código da programação;
        String codProgramacao;

        // Pegando o código da programação;
        codProgramacao = JOptionPane.showInputDialog(null, "Digite o código da programação para busca-lo", "Buscar Programação", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            ResultSet programacao = new FestivalCinemaGramadoDao().buscarProgramacao(codProgramacao);

            if (programacao.next()) { // Se a programação for encontrada;
                // Variáveis para pegar todos os dados da programação;
                String idFilme, idProgramacao, local, data, hora, info;

                // Atribuindo todos os dados da programação;
                idFilme = programacao.getString("id_sub_film");
                idProgramacao = programacao.getString("id_prog_film");
                local = programacao.getString("local_prog_film");
                data = programacao.getString("data_prog_film");
                hora = programacao.getString("hora_prog_film");
                info = programacao.getString("info_prog_film");

                // Instanciando a classe "AlterarProgramaçãoFilmes" para passar os dados das variáveis;
                new AlterarProgramacaoFilmes(idFilme, idProgramacao, local, data, hora, info).setVisible(true);

            } else { // Se a programação não for encontrada;
                JOptionPane.showMessageDialog(null, "Programação não encontrada", "Buscar Programação", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarProgramacaoActionPerformed

    private void itmExcluirProgramacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirProgramacaoActionPerformed
        // Variável para pegar o código da programação;
        String codProgramacao;

        // Pegando o código da programação;
        codProgramacao = JOptionPane.showInputDialog(null, "Digite o código da programação para a sua exclusão", "Excluir Programação", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Instanciando a classe dao que contém a parte da conexão e os comandos SQL;
            int retorno = new FestivalCinemaGramadoDao().excluirProgramacao(codProgramacao);

            if (retorno == 1) { // Se a programação for encontrada e seus dados excluidos;
                JOptionPane.showMessageDialog(null, "Programação excluída com sucesso", "Excluir Programação", JOptionPane.INFORMATION_MESSAGE);

            } else { // Se a programação não for encontrada;
                JOptionPane.showMessageDialog(null, "Programação não encontrada", "Excluir Programação", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_itmExcluirProgramacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarEventos;
    private javax.swing.JMenuItem itmAlterarFilme;
    private javax.swing.JMenuItem itmAlterarInfoUsuario;
    private javax.swing.JMenuItem itmAlterarProgramacao;
    private javax.swing.JMenuItem itmBuscarEventos;
    private javax.swing.JMenuItem itmBuscarFilme;
    private javax.swing.JMenuItem itmBuscarProgramacao;
    private javax.swing.JMenuItem itmBuscarUsuario;
    private javax.swing.JMenuItem itmCadastrarEventos;
    private javax.swing.JMenuItem itmCadastrarFilme;
    private javax.swing.JMenuItem itmCadastrarProgramacao;
    private javax.swing.JMenuItem itmExcluirEventos;
    private javax.swing.JMenuItem itmExcluirFilme;
    private javax.swing.JMenuItem itmExcluirProgramacao;
    private javax.swing.JMenuItem itmExcluirUsuario;
    private javax.swing.JMenuItem itmListarEventos;
    private javax.swing.JMenuItem itmListarFilme;
    private javax.swing.JMenuItem itmListarUsuario;
    private javax.swing.JMenuItem itmVerFilmes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblImagemPrincipal;
    private javax.swing.JMenu mnuEventosParalelos;
    private javax.swing.JMenu mnuMaisInformacoes;
    private javax.swing.JMenu mnuProgramacaoFilmes;
    private javax.swing.JMenu mnuSubmissaoFilmes;
    private javax.swing.JMenu mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
