/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.FestivalCinemaGramadoDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author arauj
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    public MenuPrincipal(String tipoUsu) {
        initComponents();

        if (tipoUsu.equalsIgnoreCase("Visitante")) {
            itmBuscarUsuario.setVisible(false);
            itmListarUsuario.setVisible(false);
            itmExcluirUsuario.setVisible(false);
            mnuSubmissao.setVisible(false);

        } else if (tipoUsu.equalsIgnoreCase("Cineasta")) {
           // itmBuscarUsuario.setVisible(false);
           // itmListarUsuario.setVisible(false);
           // itmExcluirUsuario.setVisible(false);

        } else if (tipoUsu.equalsIgnoreCase("Avaliador")) {
            itmBuscarUsuario.setVisible(false);
            itmListarUsuario.setVisible(false);
            itmExcluirUsuario.setVisible(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuario = new javax.swing.JMenu();
        itmAlterarInfoUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmBuscarUsuario = new javax.swing.JMenuItem();
        itmListarUsuario = new javax.swing.JMenuItem();
        itmExcluirUsuario = new javax.swing.JMenuItem();
        mnuProgramacao = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itmAlterarProgramacao = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuSubmissao = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        itmExcluirSubmissao = new javax.swing.JMenuItem();
        mnuEventosParalelos = new javax.swing.JMenu();
        mnuMaisInformacoes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/img-festival-cinema-full.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -30, 820, 560);

        mnuUsuario.setText("Usuario");

        itmAlterarInfoUsuario.setText("Alterar Informações");
        itmAlterarInfoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarInfoUsuarioActionPerformed(evt);
            }
        });
        mnuUsuario.add(itmAlterarInfoUsuario);
        mnuUsuario.add(jSeparator1);

        itmBuscarUsuario.setText("Buscar");
        itmBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuario.add(itmBuscarUsuario);

        itmListarUsuario.setText("Listar");
        mnuUsuario.add(itmListarUsuario);

        itmExcluirUsuario.setText("Excluir");
        mnuUsuario.add(itmExcluirUsuario);

        jMenuBar1.add(mnuUsuario);

        mnuProgramacao.setText("Programação dos Filmes");

        jMenuItem2.setText("Listar Programação");
        mnuProgramacao.add(jMenuItem2);
        mnuProgramacao.add(jSeparator2);

        itmAlterarProgramacao.setText("Alterar");
        mnuProgramacao.add(itmAlterarProgramacao);

        jMenuItem1.setText("Buscar");
        mnuProgramacao.add(jMenuItem1);

        jMenuItem3.setText("Excluir");
        mnuProgramacao.add(jMenuItem3);

        jMenuBar1.add(mnuProgramacao);

        mnuSubmissao.setText("Submissão de Filmes");

        jMenuItem4.setText("Cadastrar Filme");
        mnuSubmissao.add(jMenuItem4);

        jMenuItem5.setText("Alterar Informações");
        mnuSubmissao.add(jMenuItem5);

        jMenuItem6.setText("Buscar");
        mnuSubmissao.add(jMenuItem6);

        jMenuItem7.setText("Listar");
        mnuSubmissao.add(jMenuItem7);

        itmExcluirSubmissao.setText("Excluir");
        mnuSubmissao.add(itmExcluirSubmissao);

        jMenuBar1.add(mnuSubmissao);

        mnuEventosParalelos.setText("Eventos Paralelos");
        jMenuBar1.add(mnuEventosParalelos);

        mnuMaisInformacoes.setText("Mais Informações");
        jMenuBar1.add(mnuMaisInformacoes);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(820, 536));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarUsuarioActionPerformed
        String cpfUsu;

        cpfUsu = JOptionPane.showInputDialog(null, "Digite o CPF do usuário para continuar", "Buscar Usuário", JOptionPane.INFORMATION_MESSAGE);

        try {
            ResultSet usuario = new FestivalCinemaGramadoDao().buscarUsuario(cpfUsu);

            if (usuario.next()) {
                String nome, sobrenome, cpf, email, senha, tipoUsu;

                nome = usuario.getString("nome_usu");
                sobrenome = usuario.getString("sobrenome_usu");
                cpf = usuario.getString("cpf_usu");
                email = usuario.getString("email_usu");
                senha = usuario.getString("senha_usu");
                tipoUsu = usuario.getString("tipo_usu");

                JOptionPane.showMessageDialog(null, "Usuário: " + nome + " " + sobrenome
                        + "\n" + "CPF: " + cpf
                        + "\n" + "E-Mail: " + email
                        + "\n" + "Senha: " + senha
                        + "\n" + "Tipo de Usuário: " + tipoUsu, "Dados do usuário", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        } 
    }//GEN-LAST:event_itmBuscarUsuarioActionPerformed

    private void itmAlterarInfoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarInfoUsuarioActionPerformed
     String cpfUsu;

        cpfUsu = JOptionPane.showInputDialog(null, "Digite o seu CPF para alterar o seus dados", "Alterar Dados", JOptionPane.INFORMATION_MESSAGE);

        try {
            ResultSet usuario = new FestivalCinemaGramadoDao().buscarUsuario(cpfUsu);

            if (usuario.next()) {
                String nome, sobrenome, cpf, email, senha, tipoUsu;

                nome = usuario.getString("nome_usu");
                sobrenome = usuario.getString("sobrenome_usu");
                cpf = usuario.getString("cpf_usu");
                email = usuario.getString("email_usu");
                senha = usuario.getString("senha_usu");
                tipoUsu = usuario.getString("tipo_usu");

                new AlterarDadosUsu(nome, sobrenome, cpf, email, senha, tipoUsu).setVisible(true);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        } 
    }//GEN-LAST:event_itmAlterarInfoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarInfoUsuario;
    private javax.swing.JMenuItem itmAlterarProgramacao;
    private javax.swing.JMenuItem itmBuscarUsuario;
    private javax.swing.JMenuItem itmExcluirSubmissao;
    private javax.swing.JMenuItem itmExcluirUsuario;
    private javax.swing.JMenuItem itmListarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuEventosParalelos;
    private javax.swing.JMenu mnuMaisInformacoes;
    private javax.swing.JMenu mnuProgramacao;
    private javax.swing.JMenu mnuSubmissao;
    private javax.swing.JMenu mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
